function [obj, grad] = generatedObjective(inputVariables, extraParams)
%generatedObjective Compute objective function value
%
%   This function computes the objective value.
%   Update the generated code to add the objective gradient computation.
%
%   OBJ = generatedObjective(INPUTVARIABLES, EXTRAPARAMS) computes the
%   objective value OBJ at the point INPUTVARIABLES, using the extra
%   parameters in EXTRAPARAMS.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES, EXTRAPARAMS)
%   additionally computes the objective gradient value GRAD at the current
%   point.
%
%   Auto-generated by prob2struct on 21-Mar-2021 17:59:11

%% Map solver-based variables to problem-based.
u = inputVariables(:);

%% Insert gradient calculation here.
% If you include a gradient, notify the solver by setting the
% SpecifyObjectiveGradient option to true.
if nargout > 1
    grad = [];
end

%% Compute objective function.
% generatedFunction1 = @(u,s,r,u_prev)-dot(u.*s,r)/(dot(u,s)-eta*sum(abs(u-u_prev)))+eta*sum(abs(u-u_prev));
generatedFunction1 = extraParams{4};
obj = generatedFunction1(u, extraParams{1}, extraParams{2}, extraParams{3});

end